-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-04-30 23:49:02 MAGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
-- Student number: 30377080
-- Student name: Cong Son Huynh

SET ECHO ON;
SPOOL mh_schema_output.txt;

DROP SEQUENCE cost_center_centercode_seq;

DROP SEQUENCE doctor_doctorid_seq;

DROP SEQUENCE item_itemcode_seq;

DROP SEQUENCE nurse_nurseid_seq;

DROP SEQUENCE patient_patientid_seq;

DROP SEQUENCE procedure_information_proccode;

DROP SEQUENCE ward_wardcode_seq;

DROP TABLE admission CASCADE CONSTRAINTS;

DROP TABLE allocation CASCADE CONSTRAINTS;

DROP TABLE bed CASCADE CONSTRAINTS;

DROP TABLE cost_center CASCADE CONSTRAINTS;

DROP TABLE doctor CASCADE CONSTRAINTS;

DROP TABLE extra_item CASCADE CONSTRAINTS;

DROP TABLE item CASCADE CONSTRAINTS;

DROP TABLE new_bed CASCADE CONSTRAINTS;

DROP TABLE nurse CASCADE CONSTRAINTS;

DROP TABLE patient CASCADE CONSTRAINTS;

DROP TABLE procedure CASCADE CONSTRAINTS;

DROP TABLE procedure_information CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE ward CASCADE CONSTRAINTS;

CREATE TABLE admission (
    patientid       NUMBER(7) NOT NULL,
    admissiondate   DATE NOT NULL,
    dischargedate   DATE,
    doctorid        NUMBER(7) NOT NULL,
    bednum          NUMBER(5) NOT NULL,
    wardcode        NUMBER(7) NOT NULL
);

COMMENT ON COLUMN admission.patientid IS
    'Unique patient ID';

COMMENT ON COLUMN admission.admissiondate IS
    'Date and time of patient''s admission';

COMMENT ON COLUMN admission.dischargedate IS
    'Date and time of patient''s discharge';

COMMENT ON COLUMN admission.doctorid IS
    'Doctor ID';

COMMENT ON COLUMN admission.bednum IS
    'Bed number';

COMMENT ON COLUMN admission.wardcode IS
    'Ward code';

ALTER TABLE admission ADD CONSTRAINT admission_pk PRIMARY KEY ( admissiondate,
                                                                patientid );

CREATE TABLE allocation (
    nurseid     NUMBER(7) NOT NULL,
    startdate   DATE NOT NULL,
    enddate     DATE,
    wardcode    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN allocation.nurseid IS
    'Nurse ID';

COMMENT ON COLUMN allocation.startdate IS
    'The initial date a nurse is assigned to work in a ward';

COMMENT ON COLUMN allocation.enddate IS
    'The date a nurse finished working  in a ward';

COMMENT ON COLUMN allocation.wardcode IS
    'Ward code';

ALTER TABLE allocation ADD CONSTRAINT nurse_allocation_pk PRIMARY KEY ( nurseid,
                                                                        startdate
                                                                        );

CREATE TABLE bed (
    wardcode   NUMBER(7) NOT NULL,
    bednum     NUMBER(5) NOT NULL,
    bedphone   CHAR(10),
    bedtype    CHAR(10) NOT NULL
);

COMMENT ON COLUMN bed.wardcode IS
    'Ward code';

COMMENT ON COLUMN bed.bednum IS
    'Bed number';

COMMENT ON COLUMN bed.bedphone IS
    'Bed phone number';

COMMENT ON COLUMN bed.bedtype IS
    'Bed type';

ALTER TABLE bed ADD CONSTRAINT bed_pk PRIMARY KEY ( bednum,
                                                    wardcode );

CREATE TABLE cost_center (
    centercode      NUMBER(7) NOT NULL,
    cenntertitle    VARCHAR2(50) NOT NULL,
    cantermanager   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN cost_center.centercode IS
    'Cost center code';

COMMENT ON COLUMN cost_center.cenntertitle IS
    'Center''s title';

COMMENT ON COLUMN cost_center.cantermanager IS
    'Cneter''s manager name';

ALTER TABLE cost_center ADD CONSTRAINT cost_center_pk PRIMARY KEY ( centercode );

CREATE TABLE doctor (
    doctorid      NUMBER(7) NOT NULL,
    doctorfname   VARCHAR2(50) NOT NULL,
    doctorlname   VARCHAR2(50) NOT NULL,
    doctorphone   CHAR(10) NOT NULL
);

COMMENT ON COLUMN doctor.doctorid IS
    'Doctor ID';

COMMENT ON COLUMN doctor.doctorfname IS
    'Doctor first name';

COMMENT ON COLUMN doctor.doctorlname IS
    'Doctor last name';

COMMENT ON COLUMN doctor.doctorphone IS
    'Doctor phone number';

ALTER TABLE doctor ADD CONSTRAINT doctor_pk PRIMARY KEY ( doctorid );

CREATE TABLE extra_item (
    patientid         NUMBER(7) NOT NULL,
    procdate          DATE NOT NULL,
    itemcode          NUMBER(7) NOT NULL,
    itemquant         NUMBER(4) NOT NULL,
    itemtotalcharge   NUMBER(7, 2) NOT NULL,
    admissiondate     DATE NOT NULL,
    patientid2        NUMBER(7) NOT NULL,
    admissiondate2    DATE NOT NULL
);

ALTER TABLE extra_item ADD CONSTRAINT chk_itemquant CHECK ( itemquant > 0 );

ALTER TABLE extra_item ADD CHECK ( itemtotalcharge > 0 );

COMMENT ON COLUMN extra_item.patientid IS
    'Unique patient ID';

COMMENT ON COLUMN extra_item.procdate IS
    'Date and time procedure is performed';

COMMENT ON COLUMN extra_item.itemcode IS
    'Item code';

COMMENT ON COLUMN extra_item.itemquant IS
    'Item''s quantity used for procedure';

COMMENT ON COLUMN extra_item.itemtotalcharge IS
    'Equals item''s quantity used multiplied by item''s price';

COMMENT ON COLUMN extra_item.admissiondate IS
    'Date and time of patient''s admission';

COMMENT ON COLUMN extra_item.patientid2 IS
    'Unique patient ID';

COMMENT ON COLUMN extra_item.admissiondate2 IS
    'Date and time of patient''s admission';

ALTER TABLE extra_item
    ADD CONSTRAINT used_items_pk PRIMARY KEY ( patientid2,
                                               procdate,
                                               admissiondate2,
                                               itemcode );

CREATE TABLE item (
    itemcode     NUMBER(7) NOT NULL,
    centercode   NUMBER(7) NOT NULL,
    itemdesc     VARCHAR2(50) NOT NULL,
    itemstock    NUMBER(5) NOT NULL,
    itemprice    NUMBER(7, 2) NOT NULL
);

ALTER TABLE item ADD CONSTRAINT chk_itemstock CHECK ( itemstock >= 0 );

ALTER TABLE item ADD CONSTRAINT chk_itemprice CHECK ( itemprice > 0 );

COMMENT ON COLUMN item.itemcode IS
    'Item code';

COMMENT ON COLUMN item.centercode IS
    'Cost center code';

COMMENT ON COLUMN item.itemdesc IS
    'Item description';

COMMENT ON COLUMN item.itemstock IS
    'Item current stock';

COMMENT ON COLUMN item.itemprice IS
    'Item price';

ALTER TABLE item ADD CONSTRAINT item_pk PRIMARY KEY ( itemcode );

CREATE TABLE new_bed (
    patientid       NUMBER(7) NOT NULL,
    admissiondate   DATE NOT NULL,
    newbeddate      DATE NOT NULL,
    wardcode        NUMBER(7) NOT NULL,
    bednum          NUMBER(5) NOT NULL
);

COMMENT ON COLUMN new_bed.patientid IS
    'Unique patient ID';

COMMENT ON COLUMN new_bed.admissiondate IS
    'Date and time of patient''s admission';

COMMENT ON COLUMN new_bed.newbeddate IS
    'Date and time the patient is assigned to a new bed/ward';

COMMENT ON COLUMN new_bed.wardcode IS
    'Ward code';

COMMENT ON COLUMN new_bed.bednum IS
    'Bed number';

ALTER TABLE new_bed
    ADD CONSTRAINT bed_assignment_pk PRIMARY KEY ( patientid,
                                                   admissiondate,
                                                   newbeddate );

CREATE TABLE nurse (
    nurseid      NUMBER(7) NOT NULL,
    nursefname   VARCHAR2(50) NOT NULL,
    nurselname   VARCHAR2(50) NOT NULL,
    nursephone   CHAR(10) NOT NULL,
    nursecert    CHAR(1) NOT NULL
);

COMMENT ON COLUMN nurse.nurseid IS
    'Nurse ID';

COMMENT ON COLUMN nurse.nursefname IS
    'Nurse first name';

COMMENT ON COLUMN nurse.nurselname IS
    'Nurse last name';

COMMENT ON COLUMN nurse.nursephone IS
    'Nurse phone';

COMMENT ON COLUMN nurse.nursecert IS
    'Certification for work with children';

ALTER TABLE nurse ADD CONSTRAINT nurse_pk PRIMARY KEY ( nurseid );

CREATE TABLE patient (
    patientid     NUMBER(7) NOT NULL,
    firstname     VARCHAR2(50) NOT NULL,
    lastname      VARCHAR2(50) NOT NULL,
    dateofbirth   DATE NOT NULL,
    contactnum    CHAR(10) NOT NULL
);

COMMENT ON COLUMN patient.patientid IS
    'Unique patient ID';

COMMENT ON COLUMN patient.firstname IS
    'Patient''s first name';

COMMENT ON COLUMN patient.lastname IS
    'Patient''s last name';

COMMENT ON COLUMN patient.dateofbirth IS
    'Patient''s date of birth';

COMMENT ON COLUMN patient.contactnum IS
    'Patient''s emergency contact number';

ALTER TABLE patient ADD CONSTRAINT patient_pk PRIMARY KEY ( patientid );

CREATE TABLE procedure (
    patientid          NUMBER(7) NOT NULL,
    procdate           DATE NOT NULL,
    admissiondate      DATE NOT NULL,
    proccode           NUMBER(7) NOT NULL,
    reqdoctorid        NUMBER(7) NOT NULL,
    perfdoctorid       NUMBER(7),
    extratotalcharge   NUMBER(7, 2),
    patientid1         NUMBER(7) NOT NULL,
    admissiondate1     DATE NOT NULL
);

ALTER TABLE procedure ADD CHECK ( extratotalcharge >= 0 );

COMMENT ON COLUMN procedure.patientid IS
    'Unique patient ID';

COMMENT ON COLUMN procedure.procdate IS
    'Date and time procedure is performed';

COMMENT ON COLUMN procedure.admissiondate IS
    'Date and time of patient''s admission';

COMMENT ON COLUMN procedure.proccode IS
    'Procedure code';

COMMENT ON COLUMN procedure.reqdoctorid IS
    'Doctor ID';

COMMENT ON COLUMN procedure.perfdoctorid IS
    'Doctor ID';

COMMENT ON COLUMN procedure.extratotalcharge IS
    'Total charged fees for extra items';

COMMENT ON COLUMN procedure.patientid1 IS
    'Unique patient ID';

COMMENT ON COLUMN procedure.admissiondate1 IS
    'Date and time of patient''s admission';

ALTER TABLE procedure
    ADD CONSTRAINT procedure_pk PRIMARY KEY ( procdate,
                                              patientid1,
                                              admissiondate1 );

CREATE TABLE procedure_information (
    proccode       NUMBER(7) NOT NULL,
    procname       VARCHAR2(50) NOT NULL,
    procdesc       VARCHAR2(4000) NOT NULL,
    procduration   NUMBER(3) NOT NULL,
    proccharge     NUMBER(7, 2) NOT NULL
);

ALTER TABLE procedure_information ADD CHECK ( procduration > 0 );

ALTER TABLE procedure_information ADD CHECK ( proccharge > 0 );

COMMENT ON COLUMN procedure_information.proccode IS
    'Procedure code';

COMMENT ON COLUMN procedure_information.procname IS
    'Procedure name';

COMMENT ON COLUMN procedure_information.procdesc IS
    'Procedure description';

COMMENT ON COLUMN procedure_information.procduration IS
    'Time required for the procedure';

COMMENT ON COLUMN procedure_information.proccharge IS
    'Procedure current standard patient cost';

ALTER TABLE procedure_information ADD CONSTRAINT procedure_information_pk PRIMARY
KEY ( proccode );

CREATE TABLE specialisation (
    doctorid   NUMBER(7) NOT NULL,
    specname   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN specialisation.doctorid IS
    'Doctor ID';

COMMENT ON COLUMN specialisation.specname IS
    'Specialisation name';

ALTER TABLE specialisation ADD CONSTRAINT specialisation_pk PRIMARY KEY ( specname
,
                                                                          doctorid
                                                                          );

CREATE TABLE ward (
    wardcode       NUMBER(7) NOT NULL,
    numbeds        NUMBER(5) NOT NULL,
    numemptybeds   NUMBER(5) NOT NULL,
    wardname       VARCHAR2(50) NOT NULL
);

ALTER TABLE ward ADD CHECK ( numbeds >= 0 );

ALTER TABLE ward ADD CHECK ( numemptybeds >= 0 );

COMMENT ON COLUMN ward.wardcode IS
    'Ward code';

COMMENT ON COLUMN ward.numbeds IS
    'Current number of  beds in the ward';

COMMENT ON COLUMN ward.numemptybeds IS
    'Current number of unused (empty) beds';

COMMENT ON COLUMN ward.wardname IS
    'Ward name';

ALTER TABLE ward ADD CONSTRAINT ward_pk PRIMARY KEY ( wardcode );

ALTER TABLE new_bed
    ADD CONSTRAINT admission_newbed FOREIGN KEY ( admissiondate,
                                                  patientid )
        REFERENCES admission ( admissiondate,
                               patientid );

ALTER TABLE procedure
    ADD CONSTRAINT admission_procedure FOREIGN KEY ( admissiondate,
                                                     patientid )
        REFERENCES admission ( admissiondate,
                               patientid );

ALTER TABLE procedure
    ADD CONSTRAINT admission_procedurev2 FOREIGN KEY ( admissiondate1,
                                                       patientid1 )
        REFERENCES admission ( admissiondate,
                               patientid );

ALTER TABLE admission
    ADD CONSTRAINT bed_admission FOREIGN KEY ( bednum,
                                               wardcode )
        REFERENCES bed ( bednum,
                         wardcode );

ALTER TABLE new_bed
    ADD CONSTRAINT bed_bedassignment FOREIGN KEY ( bednum,
                                                   wardcode )
        REFERENCES bed ( bednum,
                         wardcode );

ALTER TABLE item
    ADD CONSTRAINT costcenter_item FOREIGN KEY ( centercode )
        REFERENCES cost_center ( centercode );

ALTER TABLE admission
    ADD CONSTRAINT doctor_admission FOREIGN KEY ( doctorid )
        REFERENCES doctor ( doctorid );

ALTER TABLE procedure
    ADD CONSTRAINT doctor_perform_procedure FOREIGN KEY ( perfdoctorid )
        REFERENCES doctor ( doctorid );

ALTER TABLE procedure
    ADD CONSTRAINT doctor_prescribe_procedure FOREIGN KEY ( reqdoctorid )
        REFERENCES doctor ( doctorid );

ALTER TABLE specialisation
    ADD CONSTRAINT doctor_specialisation FOREIGN KEY ( doctorid )
        REFERENCES doctor ( doctorid );

ALTER TABLE extra_item
    ADD CONSTRAINT item_extraitem FOREIGN KEY ( itemcode )
        REFERENCES item ( itemcode );

ALTER TABLE allocation
    ADD CONSTRAINT nurse_allocation FOREIGN KEY ( nurseid )
        REFERENCES nurse ( nurseid );

ALTER TABLE admission
    ADD CONSTRAINT patient_admission FOREIGN KEY ( patientid )
        REFERENCES patient ( patientid );

ALTER TABLE extra_item
    ADD CONSTRAINT procedure_extraitems FOREIGN KEY ( procdate,
                                                      patientid2,
                                                      admissiondate2 )
        REFERENCES procedure ( procdate,
                               patientid1,
                               admissiondate1 );

ALTER TABLE procedure
    ADD CONSTRAINT procedureinfo_procedure FOREIGN KEY ( proccode )
        REFERENCES procedure_information ( proccode );

ALTER TABLE allocation
    ADD CONSTRAINT ward_allocation FOREIGN KEY ( wardcode )
        REFERENCES ward ( wardcode );

ALTER TABLE bed
    ADD CONSTRAINT ward_bed FOREIGN KEY ( wardcode )
        REFERENCES ward ( wardcode );

CREATE SEQUENCE cost_center_centercode_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE doctor_doctorid_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE item_itemcode_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE nurse_nurseid_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE patient_patientid_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE procedure_information_proccode START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE ward_wardcode_seq START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
SET ECHO OFF;